// https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations

final List<Map<String, Object>> timeZoneList = [
  {'offset': -720, 'tz': 'BIT, IDLW'},
  {'offset': -660, 'tz': 'NUT, SST'},
  {'offset': -600, 'tz': 'HST, TAHT'},
  {'offset': -570, 'tz': 'MART, MIT'},
  {'offset': -540, 'tz': 'AKST, HDT'},
  {'offset': -480, 'tz': 'AKDT, PST'},
  {'offset': -420, 'tz': 'MST, PDT'},
  {'offset': -360, 'tz': 'CST, GALT'},
  {'offset': -300, 'tz': 'EST, PET'},
  {'offset': -240, 'tz': 'AMT, AST'},
  {'offset': -210, 'tz': 'NST, NT'},
  {'offset': -180, 'tz': 'ADT, FKST'},
  {'offset': -150, 'tz': 'NDT'},
  {'offset': -120, 'tz': 'GST, UYST'},
  {'offset': -60, 'tz': 'CVT, EGT'},
  {'offset': 0, 'tz': 'GMT, UTC'},
  {'offset': 60, 'tz': 'CET, BST'},
  {'offset': 120, 'tz': 'EET, CEST'},
  {'offset': 180, 'tz': 'FET, EEST'},
  {'offset': 210, 'tz': 'IRST'},
  {'offset': 240, 'tz': 'AMT, VOLT'},
  {'offset': 270, 'tz': 'AFT, IRDT'},
  {'offset': 300, 'tz': 'PKT, TFT'},
  {'offset': 330, 'tz': 'IST, SLST'},
  {'offset': 345, 'tz': 'NPT'},
  {'offset': 360, 'tz': 'BST, VOST'},
  {'offset': 390, 'tz': 'CCT, MMT'},
  {'offset': 420, 'tz': 'CXT, THA'},
  {'offset': 480, 'tz': 'AWST, HKT'},
  {'offset': 525, 'tz': 'ACWST'},
  {'offset': 540, 'tz': 'JST, YAKT'},
  {'offset': 570, 'tz': 'ACST'},
  {'offset': 600, 'tz': 'AEST, VLAT'},
  {'offset': 630, 'tz': 'ACDT, LHST'},
  {'offset': 660, 'tz': 'AEDT, VUT'},
  {'offset': 720, 'tz': 'NZST, WAKT'},
  {'offset': 765, 'tz': 'CHAST'},
  {'offset': 780, 'tz': 'NZDT, TOT'},
  {'offset': 825, 'tz': 'CHADT'},
  {'offset': 840, 'tz': 'LINT'},
  {'offset': 2000, 'tz': 'INVLD'},
  {'offset': 2001, 'tz': 'AUTO'},
];
